---
version: 2
multicolumn: false
web-width: 1000px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/dataDump_1000fitTests_multiFit_noise_051021_density_230422/dataDump_1000fitTests_multiFit_noise_051021_densityNorm_max_230422.html
    type: html
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    folder_url: "/users/71114/articles/447808/master/folder/figures/dataDump_1000fitTests_multiFit_noise_051021_density_230422"
    url: "/users/71114/articles/447808/master/file/figures/dataDump_1000fitTests_multiFit_noise_051021_density_230422/dataDump_1000fitTests_multiFit_noise_051021_densityNorm_max_230422.html"
web-height: '1100'
export-filename: dataDump_1000fitTests_multiFit_noise_051021_densityNorm_max_230422.png
