---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/paramsComp_csv_150422/paramsComp_csv_150422.csv
    type: table
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/71114/articles/447808/master/file/figures/paramsComp_csv_150422/paramsComp_csv_150422.csv"
