---
version: 2
multicolumn: false
web-width: 800px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/output_166_1/basisPlots_090822_polProd_M0.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    folder_url: "/users/71114/articles/447808/master/folder/figures/output_166_1"
    url: "/users/71114/articles/447808/master/file/figures/output_166_1/basisPlots_090822_polProd_M0.png"
