---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/dataDump_1000fitTests_multiFit_noise_051021_BLMinput/dataDump_1000fitTests_multiFit_noise_051021_BLMinput.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    folder_url: "/users/71114/articles/447808/master/folder/figures/dataDump_1000fitTests_multiFit_noise_051021_BLMinput"
    url: "/users/71114/articles/447808/master/file/figures/dataDump_1000fitTests_multiFit_noise_051021_BLMinput/dataDump_1000fitTests_multiFit_noise_051021_BLMinput.png"
