---
version: 2
multicolumn: false
web-width: 800px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/dataDump_1000fitTests_multiFit_noise_051021_BLM_allFits_150422/dataDump_1000fitTests_multiFit_noise_051021_BLM_allFits_150422.html
    type: html
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/71114/articles/447808/master/file/figures/dataDump_1000fitTests_multiFit_noise_051021_BLM_allFits_150422/dataDump_1000fitTests_multiFit_noise_051021_BLM_allFits_150422.html"
    folder_url: "/users/71114/articles/447808/master/folder/figures/dataDump_1000fitTests_multiFit_noise_051021_BLM_allFits_150422"
export-filename: dataDump_1000fitTests_multiFit_noise_051021_BLM_allFits_150422.png
web-height: '700'
