---
version: 2
multicolumn: false
web-width: 900px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/dataDump_1000fitTests_multiFit_noise_051021_BLM_allFits_150422/dataDump_1000fitTests_multiFit_noise_051021_BLMdataAgg_090323_19-42-18.html
    type: html
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    folder_url: "/users/71114/articles/447808/master/folder/figures/dataDump_1000fitTests_multiFit_noise_051021_BLM_allFits_150422"
    url: "/users/71114/articles/447808/master/file/figures/dataDump_1000fitTests_multiFit_noise_051021_BLM_allFits_150422/dataDump_1000fitTests_multiFit_noise_051021_BLMdataAgg_090323_19-42-18.html"
export-filename: dataDump_1000fitTests_multiFit_noise_051021_BLMdataAgg_090323_19-42-12.png
web-height: '700'
