---
version: 2
multicolumn: false
web-width: 800px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/output_163_2/basisPlots_090822_BLMtable.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    folder_url: "/users/71114/articles/447808/master/folder/figures/output_163_2"
    url: "/users/71114/articles/447808/master/file/figures/output_163_2/basisPlots_090822_BLMtable.png"
